#!/usr/bin/env python3
"""Post-process generated RST so Sphinx stops warning about missing references."""

from __future__ import annotations

import re
import sys
from pathlib import Path

BASE_TYPES = [
    ("class_Object", "Object", "https://docs.godotengine.org/en/stable/classes/class_object.html"),
    ("class_RefCounted", "RefCounted", "https://docs.godotengine.org/en/stable/classes/class_refcounted.html"),
    ("class_PackedByteArray", "PackedByteArray", "https://docs.godotengine.org/en/stable/classes/class_packedbytearray.html"),
    ("class_Array", "Array", "https://docs.godotengine.org/en/stable/classes/class_array.html"),
    ("class_String", "String", "https://docs.godotengine.org/en/stable/classes/class_string.html"),
    ("class_Dictionary", "Dictionary", "https://docs.godotengine.org/en/stable/classes/class_dictionary.html"),
    ("class_int", "int", "https://docs.godotengine.org/en/stable/classes/class_int.html"),
    ("class_bool", "bool", "https://docs.godotengine.org/en/stable/classes/class_bool.html"),
    ("class_float", "float", "https://docs.godotengine.org/en/stable/classes/class_float.html"),
    ("class_Callable", "Callable", "https://docs.godotengine.org/en/stable/classes/class_callable.html"),
    ("class_PackedStringArray", "PackedStringArray", "https://docs.godotengine.org/en/stable/classes/class_packedstringarray.html"),
    ("class_Variant", "Variant", "https://docs.godotengine.org/en/stable/classes/class_variant.html"),
    ("class_Image", "Image", "https://docs.godotengine.org/en/stable/classes/class_image.html"),
    ("enum_@GlobalScope_Error", "@GlobalScope.Error", "https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#enum-globalscope-error"),
]

CLASS_OBJECT_RST = """\
:github_url: hide
:allow_comments: False

.. _class_object:

Object (Godot builtin)
======================

This is a placeholder entry so the autogenerated toctree stays valid.
See the official Godot documentation for the real class reference:
`Object on docs.godotengine.org <https://docs.godotengine.org/en/stable/classes/class_object.html>`_.
"""


def ensure_class_object(docs_dir: Path) -> None:
    path = docs_dir / "class_object.rst"
    if not path.exists() or path.read_text(encoding="utf-8") != CLASS_OBJECT_RST:
        path.write_text(CLASS_OBJECT_RST, encoding="utf-8")


def write_stub_files(docs_dir: Path) -> None:
    for label, title, url in BASE_TYPES:
        if label == "class_Object":
            continue  # handled separately
        filename = re.sub(r"[^a-z0-9_]+", "_", label.lower()) + ".rst"
        path = docs_dir / filename
        content = f""":orphan:
:github_url: hide

.. _{label}:

{title} (Godot builtin)
{'=' * (len(title) + 17)}

See `{title} on docs.godotengine.org <{url}>`_.
"""
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")


def remove_old_rst_epilog(docs_dir: Path) -> None:
    conf_path = docs_dir / "conf.py"
    text = conf_path.read_text(encoding="utf-8")
    marker = "# -- injected Godot base links --"
    if marker in text:
        text = text.split(marker)[0].rstrip() + "\n"
        conf_path.write_text(text, encoding="utf-8")


def strip_include_from_index(docs_dir: Path) -> None:
    index_path = docs_dir / "index.rst"
    include_line = ".. include:: _godot_base_types.rst"
    lines = [
        ln for ln in index_path.read_text(encoding="utf-8").splitlines()
        if ln.strip() != include_line
    ]
    index_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def remove_legacy_base_doc(docs_dir: Path) -> None:
    legacy = docs_dir / "_godot_base_types.rst"
    if legacy.exists():
        legacy.unlink()


def main() -> None:
    if len(sys.argv) != 2:
        print("Usage: postprocess_rst.py <docs_dir>", file=sys.stderr)
        sys.exit(1)

    docs_dir = Path(sys.argv[1]).resolve()
    if not docs_dir.is_dir():
        print(f"Docs directory '{docs_dir}' not found", file=sys.stderr)
        sys.exit(1)

    remove_old_rst_epilog(docs_dir)
    strip_include_from_index(docs_dir)
    remove_legacy_base_doc(docs_dir)
    ensure_class_object(docs_dir)
    write_stub_files(docs_dir)


if __name__ == "__main__":
    main()
